### ISSUE TITLE
specifying arguments for build/start

### ISSUE THREAD

**Issue by dyoder** [pandastrike/p42#6]
We can do this via the `config.yaml` file, ala Compose.

**Comment by dyoder** [comment]
Ex:

``` yaml
docker:
  run:
    net: host
```
